"""add paper usage tracking

Revision ID: 4dff2c50f330
Revises: eab4261adf2d
Create Date: 2026-09-22 23:01:27.202643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dff2c50f330'
down_revision: Union[str, Sequence[str], None] = 'eab4261adf2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'papers',
        sa.Column(
            'project_count',
            sa.Integer(),
            server_default=sa.text('0'),
            nullable=False,
        ),
    )
    op.add_column('papers', sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'last_accessed_at')
    op.drop_column('papers', 'project_count')
    # ### end Alembic commands ###
